spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone_trading_platform?serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    enabled: true
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml